export const users = [
  {
    agent_type: "Sales",
    workflows: "5",
    workfows_performed_this_month: "17",
    cost_of_workflow: "$730",
    hours_saved_this_month: 22,
    extra_notes: "Leave package at the front door.",
  },
  {
    agent_type: "Support",
    workflows: "2",
    workfows_performed_this_month: "913",
    cost_of_workflow: "$290",
    hours_saved_this_month: "114",
    extra_notes: "Ring the doorbell upon arrival.",
  },
  {
    agent_type: "Finance & Audit",
    workflows: "3",
    workfows_performed_this_month: "451",
    cost_of_workflow: "$585",
    hours_saved_this_month: "1008",
    extra_notes: "Please call before arriving.",
  },
  {
    agent_type: "John Doe",
    workflows: "555-1234",
    workfows_performed_this_month: "123 Elm Street, Springfield, IL",
    cost_of_workflow: "10:00 AM",
    DSD: "2024-07-25",
    extra_notes: "Leave package at the front door.",
  },
  {
    agent_type: "Jane Smith",
    workflows: "555-5678",
    workfows_performed_this_month: "456 Oak Avenue, Metropolis, NY",
    cost_of_workflow: "2:00 PM",
    DSD: "2024-07-26",
    extra_notes: "Ring the doorbell upon arrival.",
  },
  {
    agent_type: "Alice Johnson",
    workflows: "555-8765",
    workfows_performed_this_month: "789 Pine Road, Gotham, NJ",
    cost_of_workflow: "4:00 PM",
    DSD: "2024-07-27",
    extra_notes: "Please call before arriving.",
  },
];

export const dynamic = [
  {
    order_id: 1,
    name: "Sabeeh Arif",
    phone_number: "923353302879",
    address: "ABC - street 3, New York City",
    parcel_delivery_time: "8:30 pm",
    parcel_delivery_date: "2023-07-30",
    extra_notes: "The user requested the package be delivered in...",
    status: "Out for delivery",
    products: ["cups", "table mat"],
  },
  {
    order_id: 2,
    name: "Jerry White",
    phone_number: "923321639988",
    address: "bhth86 block b, house number e 151",
    parcel_delivery_time: "08:00 pm",
    parcel_delivery_date: "2024-07-25",
    extra_notes: "The user requested the parcel to be placed on...",
    status: "Out for delivery",
    products: ["cups", "table mat"],
  },
  {
    order_id: 3,
    name: "shuja",
    phone_number: "923060940135",
    address: "Empty Response",
    parcel_delivery_time: "2.00 am",
    parcel_delivery_date: "2024-07-29",
    extra_notes: "Empty Response",
    status: "Out for delivery",
    products: ["cups", "table mat"],
  },
  {
    order_id: 4,
    name: "abuzar",
    phone_number: "923354256862",
    address: "Empty Response",
    parcel_delivery_time: "2.00 am",
    parcel_delivery_date: "2024-07-29",
    extra_notes: "Empty Response",
    status: "Out for delivery",
    products: ["cups", "table mat"],
  },
  {
    order_id: 5,
    name: "Adil kazmi",
    phone_number: "923151702008",
    address: "house no 301 block b DHA phase 6 Lahore",
    parcel_delivery_time: "10.00am",
    parcel_delivery_date: "2024-08-01",
    extra_notes: null,
    status: "Out for delivery",
    products: ["cups", "table mat"],
  },
];
